# services:
#   sudoku-server:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: sudoku-server
#     ports:
#       - "8080:8080"
#     environment:
#       - WECHAT_APPID=${WECHAT_APPID}
#       - WECHAT_SECRET=${WECHAT_SECRET}
#       - DATABASE_URL=${DATABASE_URL}
#       - RUST_LOG=info
#       - HOST=0.0.0.0
#       - PORT=8080
#     restart: unless-stopped

services:
  sudoku-server:
    # image: sudu-game-server:latest # 使用已构建的镜像
    build: .
    container_name: sudu-game-server
    ports:
      - "8080:8080" # 主机端口:容器端口
    environment:
      # 从 .env 文件或宿主环境变量中读取
      - WECHAT_APPID=${WECHAT_APPID}
      - WECHAT_SECRET=${WECHAT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=${RUST_LOG:-debug} # 默认 info，可覆盖
      - HOST=0.0.0.0
      - PORT=8080
    restart: unless-stopped
